### ISSUE TITLE
mps-player don't work

### ISSUE THREAD

**Issue by yeion7** [np1/mps#75]
each i shearch video the result is https://youtube.com/devicesupport , actually exist a solucion?

**Comment by JamesCass** [comment]
I get the same thing.  Looks like YouTube made a change.

**Comment by np1** [comment]
Hi, I think you meant to log this issue at https://github.com/np1/mps-youtube

This is the issue tracker for mps which is a separate application and has nothing to do with YouTube.

Anyway, the issue you report has been resolved in the 0.2.4 version of mps-youtube.

**Comment by JamesCass** [comment]
Ahh, my bad, sorry.  Thanks for the clarificaiton.
