### ISSUE TITLE
ImportError: No module named request...

### ISSUE THREAD

**Issue by conceptrat** [np1/mps#76]
Howdy all,

This should probably be in the FAQ/Wiki but because it causes an error I figured people might be searching the issues for it.  So...

When I quit out of "mpsyt" I received a message "A newer version is available (0.2.5)".  So I ran through the standard update procedure, for me in Ubuntu, of "sudo pip install mps-youtube --upgrade" which dutifully upgraded "mpsyt" to 0.2.5.  Upon running "mpsyt" again I was presented with the following error:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request

After a bit of head scratching, I read the latest changelog and saw the mention of version 0.2.5 only supporting Python 3 up.  So this has occurred because I was using the Python 2.7 version of "pip" which appears to be the default when running "pip", even if you have the Python 3 (in my case 3.4) version installed.  So the solution is to install the Python 3 version of "pip" (this can be done alongside the Python 2.7 version) with the following:

    sudo aptitude install python3-pip

After this has installed along with it's dependencies you can then uninstall the "mpsyt" which is installed under Python 2 with the following:

    sudo pip uninstall mps-youtube

Note: I installed for all users hence the sudo leave this off if if you installed just for yourself.

You should see something similar to the following:

```
Uninstalling mps-youtube:
  /usr/local/bin/mpsyt
  /usr/local/lib/python2.7/dist-packages/mps_youtube-0.2.5.egg-info
  /usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.py
  /usr/local/lib/python2.7/dist-packages/mps_youtube/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/mps_youtube/main.py
  /usr/local/lib/python2.7/dist-packages/mps_youtube/main.pyc
  /usr/local/lib/python2.7/dist-packages/mps_youtube/mpris.py
  /usr/local/lib/python2.7/dist-packages/mps_youtube/mpris.pyc
  /usr/local/lib/python2.7/dist-packages/mps_youtube/terminalsize.py
  /usr/local/lib/python2.7/dist-packages/mps_youtube/terminalsize.pyc
  /usr/local/share/applications/mps-youtube.desktop
Proceed (y/n)? y
  Successfully uninstalled mps-youtube
```

Obviously you're answering "y" to the "Proceed (y/n)?" question ;)

Now install "mpsyt" under Python 3 with the following:

    sudo pip3 install mps-youtube (again with the comment about "sudo")

You should see something similar to the following:

```
Downloading/unpacking mps-youtube
  Downloading mps-youtube-0.2.5-2.tar.gz (54kB): 54kB downloaded
  Running setup.py (path:/tmp/pip_build_root/mps-youtube/setup.py) egg_info for package mps-youtube
    
Downloading/unpacking pafy>=0.3.74 (from mps-youtube)
  Downloading pafy-0.3.74-py2.py3-none-any.whl
Installing collected packages: mps-youtube, pafy
  Running setup.py install for mps-youtube
    
    Installing mpsyt script to /usr/local/bin
Successfully installed mps-youtube pafy
Cleaning up...
```

That's it all good to go again :)

Cheers
Julz

**Comment by redanon** [comment]
Thanks man! that worked ,

**Comment by fredmwangi** [comment]
@np1 This should be included somewhere in the README. @conceptrat Thanks for saving me a lot of time.

**Comment by np1** [comment]
Hi, the repo for mps-youtube is at  https://github.com/mps-youtube/mps-youtube
This is the repo for mps which is a different project.
