### ISSUE TITLE
MPS not returning proper results anymore

### ISSUE THREAD

**Issue by ekianjo** [np1/mps#83]
Just used MPS today after a while not using it - I noticed that it return the same list of tracks no matter what you input. Is the interface with the service broken ?

**Comment by Hartaxfr** [comment]
Same probleme for me.

![image](https://cloud.githubusercontent.com/assets/3418195/17959581/88fe7dde-6aa1-11e6-8664-a8f90dc5fc55.png)

Allways same results

**Comment by ekianjo** [comment]
Yup I get the exact same list too.

**Comment by Joseph65** [comment]
pleer has shutdown
at pleer.net

**Comment by ekianjo** [comment]
So I guess this renders mps dead?

**Comment by Joseph65** [comment]
Here is an interesting project http://datmusic.xyz/ you can download / play music
for example # mplayer http://datmusic.xyz/acJjY:HvFmDB

**Comment by np1** [comment]
It's back up and mps is working again.
